#!/bin/bash

# Subscriber Publisher Protocol
# Copyright (C) 2021 Ted Johnson TCD 19335618 <edjohnso@tcd.ie>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Output sensor readings and publish an instruction every 10 - 20 seconds
BROKER_ADDRESS="broker:1428"
SUBSCRIBE_TOPIC="room_1_temperature"
PUBLISH_TOPIC="room_1_instructions"
INSTRUCTIONS=("on" "off" "explode")
SUBPUB="./subpub"
(
	echo subscribe "$BROKER_ADDRESS" "$SUBSCRIBE_TOPIC"
	while true; do
		sleep "$((10 + $RANDOM % 10))"
		INSTRUCTION="${INSTRUCTIONS[$RANDOM % ${#INSTRUCTIONS[@]} ]}"
		echo publish "$BROKER_ADDRESS" "$PUBLISH_TOPIC" "$INSTRUCTION"
	done
) | "$SUBPUB" 1428 "$BROKER_ADDRESS" -v none
