#!/bin/bash

# Subscriber Publisher Protocol
# Copyright (C) 2021 Ted Johnson TCD 19335618 <edjohnso@tcd.ie>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Publish a sensor reading of 20 - 40 every 10 - 30 seconds
BROKER_ADDRESS="broker:1428"
PUBLISH_TOPIC="room_1_temperature"
SUBPUB="./subpub"
(
	while true; do
		sleep "$((10 + $RANDOM % 20))"
		SENSOR_READING="$((20 + $RANDOM % 20))"°C
		echo publish "$BROKER_ADDRESS" "$PUBLISH_TOPIC" "$SENSOR_READING"
	done
) | "$SUBPUB" 1428 "$BROKER_ADDRESS"
