#ifndef SUBPUB_CONFIG_H
#define SUBPUB_CONFIG_H

#define SUBPUB_ACK_MASK 0x80
#define SUBPUB_ID_MASK 0x1f
#define SUBPUB_REQUEST_MASK 0x60
#define SUBPUB_MAX_PACKET_LEN 20

#define SUBPUB_TIMEOUT 0.5
#define SUBPUB_RETRIES 2

#define SUBPUB_IPC_PATH "/tmp/subpub"

#endif
