#ifndef SUBPUB_CONFIG_H
#define SUBPUB_CONFIG_H

#define SUBPUB_PARTIAL_TERMINATOR_CHARACTER 0x01
#define SUBPUB_ESCAPE_CHARACTER 0x02

#define SUBPUB_REQUEST_OR_RESPONSE_MASK 0x80
#define SUBPUB_ID_MASK 0x1f
#define SUBPUB_REQUEST_MASK 0x60
#define SUBPUB_MAX_PACKET_LEN 200
#define SUBPUB_UDP_PORT "14285"
#define SUBPUB_IPC_PATH "/tmp/subpub"

#define SUBPUB_INITIAL_DEADLINE_LIST_CAPACITY 4
#define SUBPUB_DEADLINE_TIMEOUT 0.5
#define SUBPUB_MAX_REQUEST_ATTEMPTS 3

#define SUBPUB_QUIT_COMMAND_LABEL "quit"
#define SUBPUB_QUIT_COMMAND_USAGE ""
#define SUBPUB_SUBSCRIBE_COMMAND_LABEL "subscribe"
#define SUBPUB_SUBSCRIBE_COMMAND_USAGE "<hostname> <port> <topic>"
#define SUBPUB_UNSUBSCRIBE_COMMAND_LABEL "unsubscribe"
#define SUBPUB_UNSUBSCRIBE_COMMAND_USAGE "<hostname> <port> <topic>"
#define SUBPUB_PUBLISH_COMMAND_LABEL "publish"
#define SUBPUB_PUBLISH_COMMAND_USAGE "<hostname> <port> <topic> <data>"

#endif
