name:                prfchk
version:             0.9.2.0
license:             BSD3
author:              "Andrew Butterfield"
maintainer:          "Andrew.Butterfield@scss.tcd.ie"
copyright:           "(c) 2017-2020 Andrew Butterfield"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         proof Checking for Haskell

dependencies:
- base >= 4.7 && < 5
- transformers
- containers
- haskeline
- haskell-src

library:
  source-dirs: src

executables:
  prfchk:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prfchk
    - haskell-src
    - directory
    - filepath

tests:
  prfchk-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prfchk
    - HUnit
    - test-framework
    - test-framework-hunit
