# Flow Forwarding
# Copyright (C) 2021 Ted Johnson TCD 19335618 <edjohnso@tcd.ie>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

version: "3"

x-contoller:
  &controller
  build: .
  image: ff:latest
  stdin_open: true
  tty: true

x-forwarder:
  &forwarder
  build: .
  image: ff:latest
  stdin_open: true
  tty: true

services:

  controller:
    <<: *controller
    container_name: controller
    command: bash -c "./flowctl"
    networks: [a,b]

  alice:
    <<: *forwarder
    container_name: alice
    command: bash -c "./flowfwd alice controller frank"
    networks: [a]
    depends_on: [controller]

  frank:
    <<: *forwarder
    container_name: frank
    command: bash -c "./flowfwd frank controller alice,bob"
    networks: [a,b]
    depends_on: [controller]

  bob:
    <<: *forwarder
    container_name: bob
    command: bash -c "./flowfwd bob controller frank"
    networks: [b]
    depends_on: [controller]

networks:
  a:
  b:
