# Flow Forwarding
# Copyright (C) 2021 Ted Johnson TCD 19335618 <edjohnso@tcd.ie>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

version: "3"

#x-contoller:
#  &controller
#  build: .
#  image: ff:latest
#  stdin_open: true
#  tty: true

x-forwarder:
  &forwarder
  build: .
  image: ff:latest
  stdin_open: true
  tty: true

services:

  #controller-abc:
  #  <<: *controller
  #  container_name: controller-abc
  #  command: ./flowctl
  #  networks:
  #    - a
  #    - b
  #    - c

  forwarder-a-1:
    <<: *forwarder
    container_name: forwarder-a-1
    command: ./flowfwd -a alice -t charlie:forwarder-ab-1 forwarder-a-2 forwarder-ab-1
    networks:
      - a
    #depends_on:
    #  - abc-controller

  forwarder-a-2:
    <<: *forwarder
    container_name: forwarder-a-2
    command: ./flowfwd -a amy forwarder-a-1 forwarder-ab-1
    networks:
      - a
    #depends_on:
    #  - abc-controller

  forwarder-ab-1:
    <<: *forwarder
    container_name: forwarder-ab-1
    command: ./flowfwd -a frank -t charlie:forwarder-bc-1 -t alice:forwarder-a-1 forwarder-a-1 forwarder-a-2 forwarder-b-1 forwarder-bc-1
    networks:
      - a
      - b
    #depends_on:
    #  - abc-controller

  forwarder-b-1:
    <<: *forwarder
    container_name: forwarder-b-1
    command: ./flowfwd -a bob forwarder-ab-1 forwarder-bc-1
    networks:
      - b
    #depends_on:
    #  - abc-controller

  forwarder-bc-1:
    <<: *forwarder
    container_name: forwarder-bc-1
    command: ./flowfwd -a fay -t charlie:forwarder-c-1 -t alice:forwarder-ab-1 forwarder-ab-1 forwarder-b-1 forwarder-c-1 forwarder-c-2
    networks:
      - b
      - c
    #depends_on:
    #  - abc-controller

  forwarder-c-1:
    <<: *forwarder
    container_name: forwarder-c-1
    command: ./flowfwd -a charlie -t alice:forwarder-bc-1 forwarder-bc-1 forwarder-c-2
    networks:
      - c
    #depends_on:
    #  - abc-controller

  forwarder-c-2:
    <<: *forwarder
    container_name: forwarder-c-2
    command: ./flowfwd -a carol forwarder-bc-1 forwarder-c-1
    networks:
      - c
    #depends_on:
    #  - abc-controller

networks:
  a:
  b:
  c:
